name: Bug
description: Report a new bug
title: "[Bug]: "
labels: ["bug"]
projects: ["kabot-io/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for take your time
    validations:
      required: false
  - type: textarea
    id: task_cb
    attributes:
      label: Current behaviour
      description: Information how it currently works
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: task_eb
    attributes:
      label: Expected behaviour
      description: Information how it should work
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: bug_fix
    attributes:
      label: Fixing the bug
      description: Information step by step how to fix the bug
      placeholder: ...
    validations:
      required: true

